ldap:
  url: ldaps://ldaptng.muenchen.de:636
  user-search-base: ou=users,ou=itm,o=lhm,c=de
  ou-search-base: o=Landeshauptstadt München,c=de

sync:
# Every date-time-minus-day > 0 is converted to 'startDateTime - date-time-minus-day' to restrict ldap user search.
  date-time-minus-day: 0
  ou-bases:
    - 'ou=Serviceteam Anwendungsentwicklung 4,ou=Servicebereich Anwendungsentwicklung,ou=Competence Center Software - Engineering (CCSE),ou=Kundenmanagement,ou=IT-M,ou=IT-Referat,o=Landeshauptstadt München,c=de'
#    - 'ou=Servicebereich Anwendungsentwicklung,ou=Competence Center Software - Engineering (CCSE),ou=Kundenmanagement,ou=IT-M,ou=IT-Referat,o=Landeshauptstadt München,c=de'
#    - ou=Competence Center Software - Engineering (CCSE),ou=Kundenmanagement,ou=IT-M,ou=IT-Referat,o=Landeshauptstadt München,c=de
#    - 'ou=RBS,ou=Kundencenter 2: RBS\, SOZ\, KULT\, RAW,ou=Kundenmanagement,ou=IT-M,ou=IT-Referat,o=Landeshauptstadt München,c=de'
#    - 'ou=Servicebereich IT-CC GIS und DZ,ou=Geschäftsbereich Kundencenter 4: BAU\, KOM\, GSR\, RKU\, PLAN\, MOR\, MSE\, AWM\, MHM,ou=Kundenmanagement,ou=IT-M,ou=IT-Referat,o=Landeshauptstadt München,c=de'
#    - 'ou=Kundencenter 2: RBS\, SOZ\, KULT\, RAW,ou=Kundenmanagement,ou=IT-M,ou=IT-Referat,o=Landeshauptstadt München,c=de'

zammad:
  assignment:
    role:
  token: changeit
  url:
    base: http://localhost:8080/api/v1/
#  capk Testinstanz
#    base: https://zammad-nginx-mpdz-zammad-dev.apps.capk.muenchen.de/api/v1/
    groups: groups
    users: users
    roles: roles

