ldap:
  url: ...
  user-search-base: ...
  ou-search-base: ...

sync:
# Every date-time-minus-day > 0 is converted to 'startDateTime - date-time-minus-day' to restrict ldap user search.
  date-time-minus-day: 7
  ou-bases:
    - dn_1
    - dn_2

zammad:
  assignment:
    role:
      name-agent: Agent
      name-erstellen: Erstellen
      name-vollzugriff: Vollzugriff
  token: ...
  url:
    base: http://...
    groups: groups
    users: users
    roles: roles

spring:
  main:
    web-application-type: none
  application:
    name: '@project.artifactId@'