server:
  port: 8080

ldap:
  url: ...
  user-search-base: ...
  ou-search-base: ...

sync:
# Every date-time-minus-day > 0 is converted to 'startDateTime - date-time-minus-day' to restrict ldap user search.
  date-time-minus-day: 7
  ou-base: ...

zammad:
  assignment:
    role:
      id: 4
  token: Token token=...
  url:
    base: http://...
    groups: groups
    users: users
    roles: roles
