ldap:
  url:

sync:
  organizational-units:
    identifier-1:
      distinguished-names:
        -
      user-search-base:
      ou-search-base:
    identifier-2:
      distinguished-names:
        -
      user-search-base:
      ou-search-base:
  message:
    from:
    to:
    subject:

zammad:
  assignment:
    role:
      # Default zammad role. Is created by zammad.
      name-agent: Agent
      # Zammad role with permission ticket.agent. Must be created.
      name-erstellen: Erstellen
      # Zammad role with permission ticket.agent. Must be created.
      name-vollzugriff: Vollzugriff
  # Create a personal access token in your Zammad profile > Token Access > Create and put it in here
  token: <token>
  url:
    base: http://<url>
    groups: groups
    users: users
    roles: roles

spring:
  main:
    web-application-type: none
  application:
    name: '@project.artifactId@'
  mail:
    host:
    port: 0
    username:
    password:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true