ldap:
  url:

sync:
# Every date-time-minus-day > 0 is converted to 'startDateTime - date-time-minus-day' to restrict ldap user search.
  organizational-units:
    identifier-1:
      distinguished-names:
        -
      user-search-base:
      ou-search-base:
    identifier-2:
      distinguished-name:
        -
      user-search-base:
      ou-search-base:

zammad:
  assignment:
    role:
      name-agent: Agent
      name-erstellen: Erstellen
      name-vollzugriff: Vollzugriff
  token: <token>
  url:
    base: http://<url>
    groups: groups
    users: users
    roles: roles

spring:
  main:
    web-application-type: none
  application:
    name: '@project.artifactId@'