server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG

ldap:
  url: ...
  user-search-base: ...
  ou-search-base: ...

sync:
  date-time-format: yyyyMMddHHmmss
  date-time-minus-day: 7
  ou-base: ...
  cron-expression: '0 15 2 ? * *'

zammad:
  assignment:
    role:
      id: 4
  token: Token token=...
  url:
    base: http://...
    groups: groups
    users: users
    roles: roles

springdoc:
  api-docs:
    path: /api-docs