name: build and test

on: [push]

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      # tag 'test' if merged to dev branch
      publish: ${{ github.ref == 'refs/heads/dev' }}
      tag-name: 'test'
