name: workflow release

on:
  workflow_call:

jobs:
  github-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - name: Update main
        run: |
          git fetch
          git merge test-release --allow-unrelated-histories

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: './pom.xml'

      - name: Remove -SNAPSHOT from Version
        id: remove_snapshot
        run: |
          mvn versions:set -DremoveSnapshot=true
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$version" >> $GITHUB_ENV

      - name: Commit Updated Version
        run: |
          git checkout main
          git add pom.xml
          git commit -m "Release version ${{ env.version }}"
          git push origin main

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${ process.env.version }`,
              sha: context.sha
            })

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Bump Version
        id: bump_version
        run: |
          mvn build-helper:parse-version versions:set \
              -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}-SNAPSHOT'
          bumped_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "bumped_version=$bumped_version" >> $GITHUB_ENV

      - name: Push Bumped Version
        run: |
          git add pom.xml
          git commit -m "chore: mvn auto version bump to $(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)"
          git checkout -b bump-version-${{ env.bumped_version }}
          git push origin bump-version-${{ env.bumped_version }}

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const pullResult = await github.rest.pulls.create({
              title: 'chore: bump release version to ${{ env.bumped_version }}',
              owner,
              repo,
              head: `bump-version-${process.env.bumped_version}`,
              base: 'test-release',
              body: [
                'This PR is auto-generated'
              ].join('\n')
            });
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: pullResult.data.number,
              assignees: ['${{ github.actor }}'],
            });
            console.log(`Pull Request created: ${pullResult.data.html_url}`);